### ISSUE TITLE
Unhandled exception when no internet connection

### ISSUE THREAD

**Issue by suragch** [Flutter-Bounty-Hunters/static_shock#128]
If there is no internet connection when calling `shock serve`, there is an unhandled exception:

```
Unhandled exception:
ClientException with SocketException: Failed host lookup: 'pub.dev' (OS Error: nodename nor servname provided, or not known, errno = 8), uri=https://pub.dev/api/packages/static_shock_cli
#0      IOClient.send (package:http/src/io_client.dart:154:7) <asynchronous suspension>
#1      BaseClient._sendUnstreamed (package:http/src/base_client.dart:93:32) <asynchronous suspension>
#2      _withClient (package:http/http.dart:167:12) <asynchronous suspension>
#3      PubUpdater._getPackageInfo (package:pub_updater/src/pub_updater.dart:87:22) <asynchronous suspension>
#4      PubUpdater.getLatestVersion (package:pub_updater/src/pub_updater.dart:57:25) <asynchronous suspension>
#5      StaticShockCliVersion.isAtLeastUpToDateWithPub (package:static_shock_cli/src/version_check.dart:42:27) <asynchronous suspension>
#6      PubVersionCheck.run (package:static_shock_cli/src/version_check.dart:23:24) <asynchronous suspension>
#7      ServeCommand.run (package:static_shock_cli/src/commands/serve_command.dart:45:5) <asynchronous suspension>
#8      CommandRunner.runCommand (package:args/command_runner.dart:212:13) <asynchronous suspension>
#9      main (file:///Users/suragch/.pub-cache/hosted/pub.dev/static_shock_cli-0.0.7/bin/static_shock_cli.dart:26:5)
<asynchronous suspension>
```

If it is possibly to run SS in offline mode, that would be the best. If that's not possible, then there could be an error message telling the user to check the internet.

**Comment by suragch** [comment]
@matthew-carroll Updated this issue in accordance with the following:

- [How to write a bug ticket](https://flutterarbiter.com/operations/how-to-write-a-bug-ticket/)
- [How to write an issue ticket](https://flutterarbiter.com/operations/how-to-write-an-issue-ticket/)
