### ISSUE TITLE
Not building - flutter_shaders - 404 Not Found

### ISSUE THREAD

**Issue by JohanScheepers** [Flutter-Bounty-Hunters/static_shock#149]
I have cloned the project  https://github.com/Flutter-Bounty-Hunters/flutter_shaders

I run shock serve from the cloned directory ...\flutter_shaders-main

When I try to launch http://localhost:4000 I get 404 Not Found

```
PS D:\FlutterProjects\Shaders\flutter_shaders-main> shock serve
Building website.

⚡ Generating a static site with Static Shock!

⚡ Clearing destination directory
Timing: 0.042s - Clear build directory - Deletes all pre-existing files in the project build directory

⚡ Applying plugins
Timing: 0.011s - Apply plugins - Every plugin configures the pipeline as desired

⚡ Loading layouts and components
Layout: \_includes\layouts\shader_page.jinja
Component: \_includes\components\google_analytics.jinja
Timing: 0.039s - Load layouts & components - Finds all layout and component files and loads them into memory

⚡ Indexing local data files into the global data index
Indexing data from: D:\FlutterProjects\Shaders\flutter_shaders-main\source\_data.yaml
Indexing data from: D:\FlutterProjects\Shaders\flutter_shaders-main\source\shaders\_data.yaml
Timing: 0.129s - Index local data - Finds all local data files and loads that data into the global pipeline index

⚡ Picking files
Picked: how-shaders-work.jinja
Picked: images\favicon\android-chrome-192x192.png
Picked: images\favicon\android-chrome-512x512.png
Picked: images\favicon\apple-touch-icon.png
Picked: images\favicon\browserconfig.xml
Picked: images\favicon\favicon-16x16.png
Picked: images\favicon\favicon-32x32.png
Picked: images\favicon\favicon.ico
Picked: images\favicon\mstile-150x150.png
Picked: images\favicon\safari-pinned-tab.svg
Picked: images\favicon\site.webmanifest
Picked: images\platform-icons.png
Picked: index.jinja
Picked: shaders\chaos\chaos.mp4
Picked: shaders\chaos\chaos.png
Picked: shaders\chaos\index.md
Picked: shaders\freeze\freeze.mp4
Picked: shaders\freeze\freeze.png
Picked: shaders\freeze\index.md
Picked: shaders\gradient-flow\gradient-flow.mp4
Picked: shaders\gradient-flow\gradient-flow.png
Picked: shaders\gradient-flow\index.md
Picked: shaders\pixelated-blur\index.md
Picked: shaders\pixelated-blur\pixelated-blur.mp4
Picked: shaders\pixelated-blur\pixelated-blur.png
Picked: shaders\ripple\index.md
Picked: shaders\ripple\ripple.mp4
Picked: shaders\ripple\ripple.png
Picked: shaders\riveo-page-curl\index.md
Picked: shaders\riveo-page-curl\riveo_page_curl.mp4
Picked: shaders\riveo-page-curl\riveo_page_curl.png
Picked: usage-guide.jinja
Picked: _includes\components\google_analytics.jinja
Picked: _includes\layouts\shader_page.jinja
Timing: 0.048s - Pick source files - Loads every desired source file into memory

⚡ Loading external data
Timing: 0.617s - Load external data - Loads all data from non-local sources, such as APIs

⚡ Loading pages and assets
Loading page: how-shaders-work.jinja
Loading asset: images\favicon\android-chrome-192x192.png
Loading asset: images\favicon\android-chrome-512x512.png
Loading asset: images\favicon\apple-touch-icon.png
Loading asset: images\favicon\browserconfig.xml
Loading asset: images\favicon\favicon-16x16.png
Loading asset: images\favicon\favicon-32x32.png
Loading asset: images\favicon\favicon.ico
Loading asset: images\favicon\mstile-150x150.png
Loading asset: images\favicon\safari-pinned-tab.svg
Loading asset: images\favicon\site.webmanifest
Loading asset: images\platform-icons.png
Loading page: index.jinja
Loading asset: shaders\chaos\chaos.mp4
Loading asset: shaders\chaos\chaos.png
Loading page: shaders\chaos\index.md
Loading asset: shaders\freeze\freeze.mp4
Loading asset: shaders\freeze\freeze.png
Loading page: shaders\freeze\index.md
Loading asset: shaders\gradient-flow\gradient-flow.mp4
Loading asset: shaders\gradient-flow\gradient-flow.png
Loading page: shaders\gradient-flow\index.md
Loading page: shaders\pixelated-blur\index.md
Loading asset: shaders\pixelated-blur\pixelated-blur.mp4
Loading asset: shaders\pixelated-blur\pixelated-blur.png
Loading page: shaders\ripple\index.md
Loading asset: shaders\ripple\ripple.mp4
Loading asset: shaders\ripple\ripple.png
Loading page: shaders\riveo-page-curl\index.md
Loading asset: shaders\riveo-page-curl\riveo_page_curl.mp4
Loading asset: shaders\riveo-page-curl\riveo_page_curl.png
Loading page: usage-guide.jinja
Loading page: _includes\components\google_analytics.jinja
Unhandled exception:
type 'String' is not a subtype of type 'YamlMap' in type cast
#0      JinjaPageLoader.loadPage (package:static_shock/src/plugins/jinja.dart:68:38)
#1      StaticShock._loadPagesAndAssets (package:static_shock/src/static_shock.dart:416:39)
<asynchronous suspension>
#2      StaticShock.generateSite (package:static_shock/src/static_shock.dart:215:5)
<asynchronous suspension>
#3      main (file:///D:/FlutterProjects/Shaders/flutter_shaders-main/bin/flutter_shaders_com.dart:33:3) 
<asynchronous suspension>
Serving a static site!
Serving at http://localhost:4000
2024-06-21T11:02:46.426732  0:00:00.010090 GET     [404] /
```

**Comment by matthew-carroll** [comment]
It looks like there's a problem with the website build:

```
type 'String' is not a subtype of type 'YamlMap' in type cast
#0      JinjaPageLoader.loadPage (package:static_shock/src/plugins/jinja.dart:68:38)
#1      StaticShock._loadPagesAndAssets (package:static_shock/src/static_shock.dart:416:39)
<asynchronous suspension>
#2      StaticShock.generateSite (package:static_shock/src/static_shock.dart:215:5)
<asynchronous suspension>
#3      main (file:///D:/FlutterProjects/Shaders/flutter_shaders-main/bin/flutter_shaders_com.dart:33:3) 
<asynchronous suspension>
```

Did you make any changes to the content?
